### ISSUE TITLE
Custom markers

### ISSUE THREAD

**Issue by omarloi** [skeelogy/ifc-ar-flood#1]
Hi Skeel, i was playing with your work, really good stuff!. 
i was wondering, is possible to make custom markers for jsartoolkit? 
For example a company logo or an image, etc.

thanks a lot!.

**Comment by skeelogy** [comment]
Hi omarloi,

I haven't tried to detect custom markers using JSARToolKit yet, so I can't be sure.

I know ARToolKit (JSARToolKit is derived from a descendant of this) has this feature. See http://www.hitl.washington.edu/artoolkit/documentation/devmulti.htm for an example. Not sure if this has been implemented all the way down to JSARToolKit though.

Best place to ask might be in the [JSARToolKit GitHub](https://github.com/kig/JSARToolKit) or in [StackOverflow](http://stackoverflow.com/).

Sorry that I don't have a concrete answer for you :(
