### ISSUE TITLE
It can be displayed on any mobile device?

### ISSUE THREAD

**Issue by proyectosanandres** [skeelogy/ifc-ar-flood#3]
It also works on devices with IOS, android, blackberry, etc?

**Comment by skeelogy** [comment]
I haven't tested it extensively yet, but from what I recall for Android, only certain web browsers can be used (I think it was Google Chrome Beta and Firefox), and the frame rate isn't fantastic.

Things might have improved by now. Test it out and see how it works out for you.

You will probably get a better answer in StackOverflow by asking about Three.js/WebGL and WebRTC support for mobile devices.

**Comment by proyectosanandres** [comment]
I need to publish augmented reality that works well in mobile devices and PC without install anything.

**Comment by skeelogy** [comment]
It's best to take this question further in StackOverflow. The community there can help you better with this question.
