### ISSUE TITLE
3d models format

### ISSUE THREAD

**Issue by proyectosanandres** [skeelogy/ifc-ar-flood#4]
What software do you use to convert 3d models js format and where 3d models are linked to their markers? 
Thank you

**Comment by skeelogy** [comment]
I used [Blender](http://www.blender.org/) to convert the 3d models to a Three.js format (and other formats). You will need to install the [plugin for Blender](https://github.com/mrdoob/three.js/tree/master/utils/exporters/blender).

The 3D models are linked to the markers via a JSON file. In your case, it should be `resources/models/models_jsartoolkit.json`. Here you can specify:
- the main marker - this marker becomes the origin in 3D space and must appear for the whole AR to work
- the correspondences between marker id and model file i.e. which model file gets loaded when a specific marker appears
